#!/bin/bash
# https://doc.omnetpp.org/omnetpp/manual/
# https://docs.omnetpp.org/tutorials/pandas/
# Nella cartella ./SimulationProject/AirTrafficControl
# Sostituire CONFIGURATION con una configurazione definita nel file omnet.ini (ex. DeterministicRegimeOverloaded)
# options: -j8 -b4 (j #CPUs, b #batch)
echo "Launching $1 simulation"
opp_makemake --deep -f -o AirTrafficControl
make clean
make all
opp_runall ./out/gcc-release/AirTrafficControl -u Cmdenv -c "$1" -f ./simulations/omnetpp.ini
# Per mandare le simulazioni sequenziali
#./out/gcc-release/AirTrafficControl -u Cmdenv -c "$1" -f ./simulations/omnetpp.ini
