//
// Generated file, do not edit! Created by nedtool 5.5 from order.msg.
//

#ifndef __BARKITCHEN_ORDER_M_H
#define __BARKITCHEN_ORDER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace barkitchen {

/**
 * Class generated from <tt>order.msg:22</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message Order
 * {
 *     double index;
 * }
 * </pre>
 */
class Order : public ::omnetpp::cMessage
{
  protected:
    double index;

  private:
    void copy(const Order& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Order&);

  public:
    Order(const char *name=nullptr, short kind=0);
    Order(const Order& other);
    virtual ~Order();
    Order& operator=(const Order& other);
    virtual Order *dup() const override {return new Order(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getIndex() const;
    virtual void setIndex(double index);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Order& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Order& obj) {obj.parsimUnpack(b);}

} // namespace barkitchen

#endif // ifndef __BARKITCHEN_ORDER_M_H

